LLAMA_STACK_URL: "http://llama-stack-service:8321"
summarize:
 enabled: false
 model: llama32
 temperature: 0.9
 max_tokens: 4096
 prompt: |
   Summarize this text.
information-search:
 enabled: false
 model: llama32
 prompt: |
   You are a helpful assistant specializing in document intelligence and academic content analysis.