LLAMA_STACK_URL: "http://llama-stack-service:8321"
shields:
 enabled: false
 # Available shields: regex, hap, prompt_injection, language_detection
 input_shields:
   - prompt_injection
   - language_detection
 output_shields:
   - hap
   - regex
summarize:
 enabled: false
 model: llama32
 temperature: 0.9
 max_tokens: 4096
 prompt: |
   Summarize this text.
information-search:
 enabled: false
 model: llama32
 vector_db_id: latest
 prompt: |
   You are a helpful assistant specializing in document intelligence and academic content analysis.