---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-backend
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"llama-stack"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canopy-backend
  template:
    metadata:
      labels:
        app: canopy-backend
    spec:
      containers:
        - name: canopy-backend
          image: quay.io/rhoai-genaiops/canopy-be:0.2
          ports:
            - containerPort: 8000
          env:
            - name: LLAMA_BASE_URL
              value: "{{ .Values.LLAMA_STACK_URL }}"
          volumeMounts:
            - mountPath: /canopy
              name: canopy-config
      volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: canopy-config.yaml
              path: canopy-config.yaml
            name: canopy-config
          name: canopy-config